resolver: lts-2.14
flags:
  ide-backend-client:
    use-cabal: false
  wai-cors:
    transformers-3: true
extra-deps: [ airship-0.3.0.0
            , wai-cors-0.2.3
            ]
docker:
  enable: true
  repo: fpco/stack-ghcjs-build
packages:
  - ./deps/JsonGrammar2
  - ./deps/ide-backend-client
  - ./deps/ide-backend-client/ide-backend-json
  - ./deps/ide-backend/ide-backend
  - ./deps/ide-backend/ide-backend-common
  - ./deps/ide-backend/ide-backend-server
  - ./deps/ide-backend/vendor/cabal/Cabal
  - ./deps/language-typescript
  - ./deps/stack-prism
  - ./soh-runner
  - ./soh-scheduler
  - ./soh-scheduler-api
  - ./soh-server
