resolver: lts-3.6
extra-deps:
   - wai-cors-0.2.3
packages:
  - ./deps/stack-ide/stack-ide
  - ./deps/stack-ide/stack-ide-api
  - ./deps/stack-ide/ide-backend/ide-backend
  - ./deps/stack-ide/ide-backend/ide-backend-server
  - ./deps/stack-ide/ide-backend/ide-backend-common
  - ./soh-runner
  - ./soh-runner-api
  - ./soh-scheduler
  - ./soh-scheduler-api
  # FIXME: turn this into an extra-dep once
  # https://github.com/helium/airship/pull/47 is merged and released to hackage.
  - location:
      git: git@github.com:mgsloan/airship
      commit: 8dd9d28ae3cce4dee27aa751b98762e22df3aaec
