resolver: lts-3.6
compiler: ghcjs-0.1.0.20150924_ghc-7.10.2
compiler-check: match-exact
packages:
  - .
  - ../deps/ghcjs-from-typescript/ghcjs-ace
  - ../deps/ghcjs-jquery
  - ../deps/ghcjs-react
  - ../deps/stack-ide/stack-ide-api
  - ../deps/stack-ide/ide-backend/ide-backend-common
  - ../soh-runner-api
  - ../soh-scheduler-api
extra-deps:
  - ghcjs-dom-0.1.1.3
  - ghcjs-websockets-0.3.0.5
